"""Deployment feature types.

Contains enums for deployment operations.
Result types are auto-generated by the @phrase decorator.
"""

from __future__ import annotations

from enum import StrEnum

__all__ = [
    # Enums
    "ApprovalStatus",
    "EnvironmentType",
    "MonitoringStatus",
    "RollbackTestStatus",
]


# =============================================================================
# Enums
# =============================================================================


class ApprovalStatus(StrEnum):
    """Deployment approval status."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"


class EnvironmentType(StrEnum):
    """Environment type classification."""

    PRODUCTION = "production"
    STAGING = "staging"
    DEVELOPMENT = "development"
    TEST = "test"


class MonitoringStatus(StrEnum):
    """Monitoring system status."""

    ACTIVE = "active"
    INACTIVE = "inactive"
    DEGRADED = "degraded"
    MAINTENANCE = "maintenance"


class RollbackTestStatus(StrEnum):
    """Rollback test result status."""

    PASSED = "passed"
    FAILED = "failed"
    NOT_TESTED = "not_tested"
    EXPIRED = "expired"
