"""AI Governance feature types.

Contains enums for AI governance operations.
Result types are auto-generated by the phrase decorator.

Regulatory basis:
- EU AI Act Article 6: High-risk AI systems classification
- EU AI Act Annex III: High-risk AI systems areas
- NYC LL144 Section 20-870: Bias audit requirements
- EU AI Act Article 9: Risk management system
- EU AI Act Article 14: Human oversight for high-risk AI
- GDPR Article 22: Automated decision-making rights
"""

from __future__ import annotations

from enum import StrEnum

__all__ = [
    "BiasAssessmentStatus",
    "HumanReviewStatus",
    "RiskLevel",
]


class RiskLevel(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class BiasAssessmentStatus(StrEnum):
    COMPLETE = "complete"
    IN_PROGRESS = "in_progress"
    EXPIRED = "expired"
    NOT_FOUND = "not_found"


class HumanReviewStatus(StrEnum):
    COMPLETE = "complete"
    PENDING = "pending"
    OVERRIDDEN = "overridden"
    NOT_FOUND = "not_found"
