"""Incident features for security incident response controls.

Complete vertical slice for incident management including:
- Incident declaration
- Containment verification
- Root cause identification

Regulatory context:
    - GDPR Article 33 (Breach notification timing)
    - HIPAA 164.308(a)(6) (Security incident procedures)
    - SOC 2 CC7.2-CC7.4 (Incident identification, response, recovery)
    - ISO 27001 A.16.1.6 (Learning from incidents)
    - NIST SP 800-61 (Computer Security Incident Handling)

Usage:
    from canon_vocab_incident import (
        # Service
        IncidentService,
        # Phrases
        require_containment_verified,
        require_incident_declared,
        require_root_cause_identified,
        verify_containment_verified,
        verify_root_cause_identified,
        # Specs classes
        RequireContainmentVerifiedSpecs,
        RequireIncidentDeclaredSpecs,
        RequireRootCauseIdentifiedSpecs,
        VerifyContainmentVerifiedSpecs,
        VerifyRootCauseIdentifiedSpecs,
        # Types
        ContainmentStatus,
        ContainmentVerificationStatus,
        RootCauseStatus,
        # Exceptions
        RequirementNotMetError,
        # Package metadata
        INCIDENT,
    )
"""

# Exceptions
from .exceptions import RequirementNotMetError

# Package metadata
from .package import INCIDENT

# Phrases
from .phrases import (
    RequireContainmentVerifiedSpecs,
    RequireIncidentDeclaredSpecs,
    RequireRootCauseIdentifiedSpecs,
    VerifyContainmentVerifiedSpecs,
    VerifyRootCauseIdentifiedSpecs,
    require_containment_verified,
    require_incident_declared,
    require_root_cause_identified,
    verify_containment_verified,
    verify_root_cause_identified,
)

# Service
from .service import IncidentService

# Types (enums only - result types auto-generated by phrases)
from .types import ContainmentStatus, ContainmentVerificationStatus, RootCauseStatus

__all__ = [
    # Package metadata
    "INCIDENT",
    # Service
    "IncidentService",
    # Types
    "ContainmentStatus",
    "ContainmentVerificationStatus",
    "RootCauseStatus",
    # Specs classes
    "RequireContainmentVerifiedSpecs",
    "RequireIncidentDeclaredSpecs",
    "RequireRootCauseIdentifiedSpecs",
    "VerifyContainmentVerifiedSpecs",
    "VerifyRootCauseIdentifiedSpecs",
    # Exceptions
    "RequirementNotMetError",
    # Phrase functions
    "require_containment_verified",
    "require_incident_declared",
    "require_root_cause_identified",
    "verify_containment_verified",
    "verify_root_cause_identified",
]
