"""Freshness feature types.

Contains type aliases for freshness operations.
Result types are auto-generated by the phrase decorator.
"""

from __future__ import annotations

from typing import Literal

__all__ = ["FreshnessStatus"]


# =============================================================================
# Type Aliases
# =============================================================================

FreshnessStatus = Literal["fresh", "stale", "expired"]
