"""Incident feature types.

Contains enums for incident operations.
Result types are auto-generated by the phrase decorator.
"""

from __future__ import annotations

from enum import StrEnum

from .status import IncidentStatus

__all__ = [
    "ContainmentStatus",
    "ContainmentVerificationStatus",
    "IncidentStatus",
    "RootCauseStatus",
]


# =============================================================================
# Enums
# =============================================================================


class ContainmentStatus(StrEnum):
    """Containment verification status values."""

    CONTAINED = "contained"  # Incident fully contained
    PARTIAL = "partial"  # Partially contained, some exposure remains
    NOT_CONTAINED = "not_contained"  # Incident not yet contained
    UNKNOWN = "unknown"  # Cannot determine (treat as not contained)


class ContainmentVerificationStatus(StrEnum):
    """Containment verification process status."""

    VERIFIED = "verified"
    PENDING = "pending"
    FAILED = "failed"
    NOT_APPLICABLE = "not_applicable"


class RootCauseStatus(StrEnum):
    """Root cause analysis status."""

    IDENTIFIED = "identified"
    IN_PROGRESS = "in_progress"
    UNKNOWN = "unknown"
    NOT_APPLICABLE = "not_applicable"
