"""Canon entity system — framework entities and domain workflow models.

Framework entities:
    entity: Entity, ContentModel, register_entity (base infrastructure)
    charter: Charter, CharterRun, PhaseExecution (governance workflows)
    evidence: Evidence, ChainEntry (immutable audit artifacts)
    consent: ConsentToken, ConsentRequest (consent management)
    document: Document (output provenance)
    policy: PolicyDefinition, PolicyDecision, PolicyAuthority, etc.
    shared: Tenant, User, Person, Organization, Employee, Session

Domain workflow entities:
    workflows.talent: HiringBrief, Interview, Job, Market, etc.
    workflows.employee: PIPPlan, PIPCheckpoint, etc.
    workflows: DocumentAccessToken, WorkflowStatus (framework-level)
"""

from .charter import (
    Charter,
    CharterContent,
    CharterRun,
    CharterRunContent,
    CharterRunStatus,
    CharterStatus,
    PhaseExecution,
    PhaseExecutionContent,
    PhaseStatus,
)
from .consent import (
    ConsentRequest,
    ConsentRequestContent,
    ConsentRequestStatus,
    ConsentScope,
    ConsentStatus,
    ConsentToken,
    ConsentTokenContent,
)
from .document import Document, DocumentContent, DocumentStatus
from .entity import (
    CANON_CONFIG,
    ContentModel,
    Entity,
    get_entity_by_table,
    get_entity_registry,
    register_entity,
    reset_entity_registry,
)
from .evidence import ChainEntry, ChainEntryContent, Evidence, EvidenceContent
from .policy import (
    PolicyAdapter,
    PolicyAdapterContent,
    PolicyAuthority,
    PolicyDecision,
    PolicyDefinition,
    PolicyDefinitionContent,
    PolicyRelease,
    PolicyReleaseContent,
    PolicyScope,
    PolicyStatus,
)
from .shared import (
    ActorAware,
    AwareOf,
    Employee,
    EmployeeAware,
    EmployeeContent,
    EmploymentStatus,
    OptActorAware,
    OptEmployeeAware,
    OptSubjectAware,
    Organization,
    OrganizationContent,
    Person,
    PersonContent,
    Session,
    SessionContent,
    SubjectAware,
    Tenant,
    TenantAware,
    TenantContent,
    User,
    UserAware,
    UserContent,
    is_aware_of,
)
from .workflows import (
    NEXT_STATUS_ON_APPROVAL,
    STATUS_TO_APPROVER_ROLE,
    ActionType,
    AIDisclosure,
    AIDisclosureContent,
    ApprovalStatus,
    ApproverRole,
    BiasAnalysis,
    BiasAnalysisContent,
    BiasCategory,
    BiasFlag,
    CalibrationResult,
    CalibrationResultContent,
    CalibrationStatus,
    Candidacy,
    CandidacyContent,
    CandidacyStatus,
    CandidateStory,
    CandidateStoryContent,
    CompetencyAssessment,
    CompetencyAssessmentContent,
    DocumentAccessPurpose,
    DocumentAccessStatus,
    DocumentAccessToken,
    DocumentAccessTokenContent,
    EvaluatorProfile,
    EvaluatorProfileContent,
    ExceptionOffer,
    ExceptionOfferContent,
    GoalStatus,
    HiringBrief,
    HiringBriefContent,
    Interview,
    InterviewContent,
    InterviewStatus,
    Job,
    JobContent,
    JobStatus,
    MarketAnalysis,
    MarketAnalysisContent,
    MarketContext,
    MarketContextContent,
    MarketMap,
    MarketMapContent,
    OfferApproval,
    OfferApprovalContent,
    OfferStatus,
    OutreachMessage,
    OutreachMessageContent,
    PIPCheckpoint,
    PIPCheckpointContent,
    PIPDecision,
    PIPDecisionContent,
    PIPOutcome,
    PIPOutcomeRecommendation,
    PIPOutcomeRecommendationContent,
    PIPPhase,
    PIPPlan,
    PIPPlanContent,
    PIPStatus,
    Recommendation,
    RiskFlag,
    Scorecard,
    ScorecardContent,
    SignalResult,
    SignalResultContent,
    SkillInference,
    SkillInferenceContent,
    StepStatus,
    StorySection,
    StorySectionContent,
    WorkflowStatus,
    WorkplaceModel,
)

__all__ = (
    # Entity system
    "CANON_CONFIG",
    "ContentModel",
    "Entity",
    "get_entity_by_table",
    "get_entity_registry",
    "register_entity",
    "reset_entity_registry",
    # Charter
    "Charter",
    "CharterContent",
    "CharterRun",
    "CharterRunContent",
    "CharterRunStatus",
    "CharterStatus",
    "PhaseExecution",
    "PhaseExecutionContent",
    "PhaseStatus",
    # Evidence
    "ChainEntry",
    "ChainEntryContent",
    "Evidence",
    "EvidenceContent",
    # Policy
    "PolicyAdapter",
    "PolicyAdapterContent",
    "PolicyAuthority",
    "PolicyDecision",
    "PolicyDefinition",
    "PolicyDefinitionContent",
    "PolicyRelease",
    "PolicyReleaseContent",
    "PolicyScope",
    "PolicyStatus",
    # Shared entities
    "Employee",
    "EmployeeContent",
    "EmploymentStatus",
    "Organization",
    "OrganizationContent",
    "Person",
    "PersonContent",
    "Session",
    "SessionContent",
    "Tenant",
    "TenantAware",
    "TenantContent",
    "User",
    "UserAware",
    "UserContent",
    # Consent
    "ConsentRequest",
    "ConsentRequestContent",
    "ConsentRequestStatus",
    "ConsentScope",
    "ConsentStatus",
    "ConsentToken",
    "ConsentTokenContent",
    # Document
    "Document",
    "DocumentContent",
    "DocumentStatus",
    # Awareness mixins
    "ActorAware",
    "AwareOf",
    "EmployeeAware",
    "OptActorAware",
    "OptEmployeeAware",
    "OptSubjectAware",
    "SubjectAware",
    "is_aware_of",
    # Workflow entities (domain)
    "HiringBrief",
    "HiringBriefContent",
    "MarketContext",
    "MarketContextContent",
    "CalibrationResult",
    "CalibrationResultContent",
    "CalibrationStatus",
    "EvaluatorProfile",
    "EvaluatorProfileContent",
    "BiasAnalysis",
    "BiasAnalysisContent",
    "BiasFlag",
    "CompetencyAssessment",
    "CompetencyAssessmentContent",
    "Interview",
    "InterviewContent",
    "InterviewStatus",
    "Recommendation",
    "Scorecard",
    "ScorecardContent",
    "MarketAnalysis",
    "MarketAnalysisContent",
    "MarketMap",
    "MarketMapContent",
    "AIDisclosure",
    "AIDisclosureContent",
    "OutreachMessage",
    "OutreachMessageContent",
    "GoalStatus",
    "PIPCheckpoint",
    "PIPCheckpointContent",
    "PIPDecision",
    "PIPDecisionContent",
    "PIPOutcome",
    "PIPOutcomeRecommendation",
    "PIPOutcomeRecommendationContent",
    "PIPPhase",
    "PIPPlan",
    "PIPPlanContent",
    "PIPStatus",
    "RiskFlag",
    "CandidateStory",
    "CandidateStoryContent",
    "SignalResult",
    "SignalResultContent",
    "SkillInference",
    "SkillInferenceContent",
    "StorySection",
    "StorySectionContent",
    "Candidacy",
    "CandidacyContent",
    "CandidacyStatus",
    "Job",
    "JobContent",
    "JobStatus",
    "ExceptionOffer",
    "ExceptionOfferContent",
    "OfferApproval",
    "OfferApprovalContent",
    # Workflow enums
    "ActionType",
    "ApprovalStatus",
    "ApproverRole",
    "BiasCategory",
    "DocumentAccessPurpose",
    "DocumentAccessStatus",
    "NEXT_STATUS_ON_APPROVAL",
    "OfferStatus",
    "STATUS_TO_APPROVER_ROLE",
    "StepStatus",
    "WorkflowStatus",
    "WorkplaceModel",
    # Framework workflow entities
    "DocumentAccessToken",
    "DocumentAccessTokenContent",
)
